Add GET /equipment/unavailibility_periods
CSR-LC/csr-be pull request #24
Opened 2023-02-28 09:48 UTC by daniilsolovey

Implemented new api to provide equipment unavailibility time periods
1) equipment_id - only one parameter
2) Returns start date, end date in response
3) Unit test for checking dates

[Feature-7207](https://jira.epam.com/jira/browse/EPMUII-7207)

2023-02-28 10:05 UTC, Sugar-pack requested changes
If I request equipment information from available equipment, I get the same error code (500) as if the equipment id was incorrect or if other problems exist. I think that the server should respond with a different code in that case.

2023-03-01 09:31 UTC, antelman107 approved these changes

2023-03-01 10:51 UTC, Sugar-pack commented on swagger.yaml
> +            $ref: "#/definitions/EquipmentUnavailabilityPeriodsResponse"
Please, do not resolve unresolved questions.

2023-03-01 11:44 UTC, Sugar-pack approved these changes
Great work

2023-03-01 12:40 UTC, merged